name: Terraform CI

on:
  push:
    branches: main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Rodar Init
        run: terraform init

      - name: Criar um plano
        run: terraform plan
